name: Deployment pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run eslint
      - name: Run npm test for server
        run: npm run test:server
      - name: Run npm test for client
        run: npm run test:client
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Run npm build
        run: npm run build
  tag_release:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  discord_notify:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'push' }}
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: ${{ needs.build_and_test.result == 'failed' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: Deployment failed
          description: New version failed to deploy
      - uses: sarisia/actions-status-discord@v1
        if: ${{ needs.build_and_test.result == 'success'}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true
          title: Successfully deployed a new version
          description: |
            Commit: ${{ github.event.head_commit.id }}
            Author: ${{ github.event.head_commit.author.name }}
            Message: ${{ github.event.head_commit.message }}